### ISSUE TITLE
[4.0.3] UPS Rates Different / Service detail pages broken

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/postie#132]
### Describe the bug

Working through the process of upgrading Postie from 3 -> 4. 

The upgrade itself seemed to work, though I had to put in the carrier (UPS), box details, and credentials all over again. Not sure if that was supposed to taken care of in the migration or not? No big deal either way.

However, I also noticed that when I go into each service (eg Ground), I'm getting a 404 not found error. Maybe a known issue?

More imporantly, I'm getting vastly different rates between versions, as if our clients' negotiated rates aren't showing up. Assuming the box packer itself hasn't been tweaked, I'm not sure what else I'm missing?

![Screenshot 2024-06-28 at 3 11 25 PM](https://github.com/verbb/postie/assets/3707869/8177395b-35e8-477c-8d38-0f0abe8994c2)

Current Prodution (Postie 3)
![Screenshot 2024-06-28 at 3 05 23 PM](https://github.com/verbb/postie/assets/3707869/41a1d53e-e8a4-4d11-aa90-7693463be9f5)

Current testing (Postie 4)
![Screenshot 2024-06-28 at 3 08 15 PM](https://github.com/verbb/postie/assets/3707869/7827c470-22de-4333-90da-9a1ba001eadc)

### Steps to reproduce

1. Upgrade Postie from 3 to 4.
2. Setup a new carrier (UPS), box sizes, etc.

### Craft CMS version

4.10.3

### Plugin version

4.0.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Ah, sorry about that. I didn't factor in the already-updated OAuth-based provider, just the older non-OAuth one. Updated for the next release.

As for the 404, that's because we switched handles for services back to their numeric ones. Other providers use strings, and that's causing issues for the route matching.

Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 4.0.3"`.

That's quite interesting! Can you send through the test info you're using (from, to, dimensions/weights). Seems like you're using the front-end to test, so either the from/to address and the contents of your cart, or send through a screenshot of the same info in the "Rates Testing" tab in the control panel for the provider.

I don't think I'll need your connection credentials and account number for negotiated rates yet. You're also welcome to send via `support@verbb.io` if you're rather send anything privately.

**Comment by RitterKnightCreative** [comment]
Excellent, thank you!

I did a little more digging and I'm wondering if UPS is changing the address classification? I'm getting this returned from UPS:
``
                                    [Code] => 110920
                                    [Description] => Ship To Address Classification is changed from Commercial to Residential
``

The weird thing is I'm not getting that with the older version. Wonder if there was any address correction going on? (I'd have to test with a commercial address to see.)

This might also explain why my client had to put a 65% markup on the current site if the rate getting spit out is too low... 

[RESPONSE.txt](https://github.com/user-attachments/files/16057258/RESPONSE.txt)
[REQUEST.txt](https://github.com/user-attachments/files/16057259/REQUEST.txt)

**Comment by engram-design** [comment]
That's a little odd, as while we support setting an address as residential it's pretty much always `false`, so I'm unsure why it's switching that back from Commercial to Residential.

But from a quick Google at other implementations out there, it seems to be common when coming from the XML API to REST API. I did just push a slight change to [shippy](https://github.com/verbb/shippy/commit/fd916c87d1db996f754e4e95284092fcae88fc0c) that was enforcing `residential = false` that might be something to do with it.

**Comment by johnnynotsolucky** [comment]
@engram-design #133 should fix the rates issue reported in this issue:

> More imporantly, I'm getting vastly different rates between versions, as if our clients' negotiated rates aren't showing up. Assuming the box packer itself hasn't been tweaked, I'm not sure what else I'm missing?

For the alert "Ship To Address Classification is changed from Commercial to Residential", we're seeing this too, but I haven't been able to work out why yet.

According to the API docs, the correct field to set in the payload to UPS is `ResidentialAddressIndicator`, however, I've tested setting that in the payload too and I'm still seeing the same alerts.
![image](https://github.com/verbb/postie/assets/4161106/14532284-c289-4696-a943-9f41d9e5666c)

After my change in #133, the difference in rates is less significant, instead its a few dollars on each rate that's returned. I suspect that that difference is possibly due to the address classification alert.

**Comment by engram-design** [comment]
This _might_ also be fixed in the latest [shippy](https://github.com/verbb/shippy) updates, which you can get early, run `composer require verbb/postie:"dev-craft-4 as 4.0.3"`.

**Comment by johnnynotsolucky** [comment]
@engram-design, even with the change from #133, and the update for the address classification, I'm still seeing the "Ship To Address Classification is changed from Commercial to Residential" message. There is also still a slight difference in the rate compared to the pre-Shippy version of Postie.

I've traced both of these to a difference in how rates are fetched from the pre-Shippy version of Postie.

Previously, the Ship To address didn't include the street lines:

```json
{
	"ShipTo": {
		"Address": {
			"City": "Los Angeles",
			"StateProvinceCode": "CA",
			"PostalCode": "90026",
			"CountryCode": "US"
		}
	}
}
```

However, the street lines are included when fetching rate information now:

```json
{
	"ShipTo": {
		"Name": "Tyrone",
		"AttentionName": "Tyrone",
		"Address": {
			"AddressLine": [
				"1514 Maltman Ave"
			],
			"City": "Los Angeles",
			"StateProvinceCode": "CA",
			"PostalCode": "90026",
			"CountryCode": "US"
		},
		"EMailAddress": "tyrone@email.com"
	}
}
```

If I remove the `AddressLine` property, then the rates are as they were before.

It seems like the rates are then more accurate since the actual address is included, not just the area information which is why there is a few dollars difference in rates now. But I can't work out why the alert is showing up when the address lines are included.

In the above example, the rate for UPS Ground without address lines is $16.90, and with address lines, it is $19.10. That looks like it should be correct to me.

**Comment by engram-design** [comment]
Thanks for investigating. I suppose we possibly should've always used the full address where provided for more accurate rates in the first place. While new rates are higher, this seems more accurate? We certainly need them accurate now in order to generate shipments and labels.

I would have thought omitting a reference to an address being residential would mean UPS set it to "auto", but that same warning keeps cropping up. I'm not sure if it's something that we can ignore or not?

**Comment by johnnynotsolucky** [comment]
> I would have thought omitting a reference to an address being residential would mean UPS set it to "auto", but that same warning keeps cropping up. I'm not sure if it's something that we can ignore or not?

Also not sure at the moment 😅

**Comment by RitterKnightCreative** [comment]
Also - testing using the UPS plugin, the Markup Rate doesn't seem to have any affect on the front end or when using the Rates Testing feature. 

If I try to change Markup Base from Percentage to Value, it reverts back to Percentage after saving.

**Comment by engram-design** [comment]
The “Markup Base” setting not saving correctly should be fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 4.0.10"`.

As for the Rates Testing, that's correct that markup doesn't appear there. This is more just for simplicity than anything, and to ensure that checking rates and responses from actual provider APIs is accurate. It's a good utility to compare against the provider's own testing utilities as well. We may end up adding a checkbox there to include markup rates if that's a concern.

With that fix in place though, rates are adjusted on the front-end for me - if you can confirm?

**Comment by RitterKnightCreative** [comment]
> We may end up adding a checkbox there to include markup rates if that's a concern.

That would be very useful to have, something like this on the test screen:

![Image](https://github.com/user-attachments/assets/0aa47d60-f5a6-41e5-82da-2f5d7c54ea65)

This would allow shop admins to preview their marked up rates without having to mess around on the front end.

> With that fix in place though, rates are adjusted on the front-end for me - if you can confirm?

This looks good to me, thanks Josh.

**Comment by RitterKnightCreative** [comment]
Also - forgot to mention, if the Origin address  in that Rates Testing screen would fill in using the actual store address, that'd save a lot of time.

**Comment by engram-design** [comment]
Updated in [4.0.12](https://github.com/verbb/postie/releases/tag/4.0.12).
